[{"name": "test.test_matrix_power.MatrixPower.test_called", "status": "errored", "message": "module 'src.matrix_power' has no attribute 'functools'", "passed": false, "points": ["p03-04.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part03-e04_matrix_power/test/test_matrix_power.py\", line 53, in test_called\n    with patch(ph(\"functools.reduce\"), wraps=functools.reduce) as preduce:\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part03-e04_matrix_power/tmc/utils.py\", line 216, in __call__\n    getattr(importlib.import_module(self.m), parts[-2])  # subpackage2.attribute\n"]}, {"name": "test.test_matrix_power.MatrixPower.test_exponents", "status": "errored", "message": "name 'np' is not defined", "passed": false, "points": ["p03-04.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part03-e04_matrix_power/test/test_matrix_power.py\", line 45, in test_exponents\n    np.testing.assert_array_almost_equal(matrix_power(a, 2), a@a, err_msg=\"Incorrect power of 2 for matrix\\n%s!\" % a)\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part03-e04_matrix_power/src/matrix_power.py\", line 5, in matrix_power\n    np.eye(2)\n"]}, {"name": "test.test_matrix_power.MatrixPower.test_multiply", "status": "errored", "message": "name 'np' is not defined", "passed": false, "points": ["p03-04.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part03-e04_matrix_power/test/test_matrix_power.py\", line 36, in test_multiply\n    a1 = matrix_power(a, i)\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part03-e04_matrix_power/src/matrix_power.py\", line 5, in matrix_power\n    np.eye(2)\n"]}, {"name": "test.test_matrix_power.MatrixPower.test_one", "status": "errored", "message": "name 'np' is not defined", "passed": false, "points": ["p03-04.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part03-e04_matrix_power/test/test_matrix_power.py\", line 23, in test_one\n    np.testing.assert_array_equal(a, matrix_power(a, 1),\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part03-e04_matrix_power/src/matrix_power.py\", line 5, in matrix_power\n    np.eye(2)\n"]}, {"name": "test.test_matrix_power.MatrixPower.test_zero", "status": "errored", "message": "name 'np' is not defined", "passed": false, "points": ["p03-04.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part03-e04_matrix_power/test/test_matrix_power.py\", line 29, in test_zero\n    np.testing.assert_array_equal(np.eye(2), matrix_power(a, 0),\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part03-e04_matrix_power/src/matrix_power.py\", line 5, in matrix_power\n    np.eye(2)\n"]}]