[{"name": "test.test_extract_numbers.ExtractNumbers.test_calls", "status": "failed", "message": "0 != 4 : Expected 4 calls of 'float'!", "passed": false, "points": ["p02-10.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part02-e10_extract_numbers/test/test_extract_numbers.py\", line 26, in test_calls\n    self.assertEqual(fl.call_count, 4, msg=\"Expected 4 calls of 'float'!\")\n"]}, {"name": "test.test_extract_numbers.ExtractNumbers.test_first", "status": "failed", "message": "Lists differ: [] != [123, 1.2, 13.2, -1]\n\nSecond list contains 4 additional elements.\nFirst extra element 0:\n123\n\n- []\n+ [123, 1.2, 13.2, -1] : Incorrect result for string abd 123 1.2 test 13.2 -1!", "passed": false, "points": ["p02-10.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part02-e10_extract_numbers/test/test_extract_numbers.py\", line 21, in test_first\n    self.assertEqual(L, [123, 1.2, 13.2, -1], msg=\"Incorrect result for string %s!\" % s)\n"]}, {"name": "test.test_extract_numbers.ExtractNumbers.test_random", "status": "failed", "message": "Lists differ: [93, -2, -28, -83, 35, -26, -42, 76, -44, [173 chars] -43] != []\n\nFirst list contains 50 additional elements.\nFirst extra element 0:\n93\n\n+ []\n- [93,\n-  -2,\n-  -28,\n-  -83,\n-  35,\n-  -26,\n-  -42,\n-  76,\n-  -44,\n-  -99,\n-  -10,\n-  45,\n-  53,\n-  36,\n-  97,\n-  -11,\n-  -15,\n-  -90,\n-  92,\n-  43,\n-  30,\n-  99,\n-  7,\n-  41,\n-  7,\n-  -94,\n-  97,\n-  -82,\n-  -70,\n-  10,\n-  69,\n-  -19,\n-  -46,\n-  32,\n-  34,\n-  60,\n-  -31,\n-  69,\n-  51,\n-  31,\n-  73,\n-  75,\n-  70,\n-  -81,\n-  -42,\n-  -9,\n-  -57,\n-  -27,\n-  -14,\n-  -43] : Incorrect result for string 93 -2 -28 -83 35 -26 -42 76 -44 -99 -10 45 53 36 97 -11 -15 -90 92 43 30 99 7 41 7 -94 97 -82 -70 10 69 -19 -46 32 34 60 -31 69 51 31 73 75 70 -81 -42 -9 -57 -27 -14 -43!", "passed": false, "points": ["p02-10.1"], "backtrace": ["  File \"/usr/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n", "  File \"/home/sonya/git/github/m1t0z/mooc-data-analysis-with-python-2021/part02-e10_extract_numbers/test/test_extract_numbers.py\", line 32, in test_random\n    self.assertEqual(L, result, msg=\"Incorrect result for string %s!\" % s)\n"]}]